### ISSUE TITLE
Error in home page

### ISSUE THREAD

**Issue by praveenkumar-alpha** [Santos-Enoque/complete_flutter_ecommerce#21]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building FeaturedCard(dirty):
'package:flutter/src/widgets/fade_in_image.dart': Failed assertion: line 159 pos 15: 'image != null': is not true.

The relevant error-causing widget was: 
  FeaturedCard file:///D:/Yolo/yolo/lib/widgets/featured_products.dart:23:22
When the exception was thrown, this was the stack: 
#2      new FadeInImage.memoryNetwork (package:flutter/src/widgets/fade_in_image.dart:159:15)
#3      FeaturedCard.build (package:yolo/widgets/featured_card.dart:43:38)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/fade_in_image.dart': Failed assertion: line 159 pos 15: 'image != null': is not true.
The relevant error-causing widget was: 
  ProductCard file:///D:/Yolo/yolo/lib/screens/home.dart:188:32
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/fade_in_image.dart': Failed assertion: line 159 pos 15: 'image != null': is not true.
The relevant error-causing widget was: 
  ProductCard file:///D:/Yolo/yolo/lib/screens/home.dart:188:32
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/fade_in_image.dart': Failed assertion: line 159 pos 15: 'image != null': is not true.
The relevant error-causing widget was: 
  ProductCard file:///D:/Yolo/yolo/lib/screens/home.dart:188:32
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/fade_in_image.dart': Failed assertion: line 159 pos 15: 'image != null': is not true.
The relevant error-causing widget was: 
  ProductCard file:///D:/Yolo/yolo/lib/screens/home.dart:188:32
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 6 of 661 libraries in 784ms.
W/ConnectionTracker(18831): Exception thrown while unbinding
W/ConnectionTracker(18831): java.lang.IllegalArgumentException: Service not registered: ls@4dfeaf
W/ConnectionTracker(18831): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1759)
W/ConnectionTracker(18831): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1786)
W/ConnectionTracker(18831): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:751)
W/ConnectionTracker(18831): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204714081@20.47.14 (120400-0):1)
W/ConnectionTracker(18831): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204714081@20.47.14 (120400-0):2)
W/ConnectionTracker(18831): 	at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204714081@20.47.14 (120400-0):9)
W/ConnectionTracker(18831): 	at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204714081@20.47.14 (120400-0):3)
W/ConnectionTracker(18831): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204714081@20.47.14 (120400-0):3)
W/ConnectionTracker(18831): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(18831): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(18831): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204714081@20.47.14 (120400-0):5)

ProductCard is throwing error

**Comment by Amit998** [comment]
Share your code.
